### ISSUE TITLE
A Problem

### ISSUE THREAD

**Issue by altair984** [SteffanPoulsen/dice-tooltip#1]
dont show the dice pooltip with better rolls for 5e

**Comment by Rykazz** [comment]
I have found that this wonderful and very helpful mod does not function for the Favourite Items Tab or the Tidy5e-Sheet.  I ask that, if you could, fix this.

**Comment by SteffanPoulsen** [comment]
The current way I calculate dice rolls is super hacky, because the api doesn't really have good support for the stuff this module is doing. But I expect that to change in 0.7.0 once that gets released soon!
