### ISSUE TITLE
Tidy5e-Sheet support

### ISSUE THREAD

**Issue by Rykazz** [SteffanPoulsen/dice-tooltip#3]
I have found that this wonderful and very helpful mod does not function for the Tidy5e-Sheet. I ask that, if you could, fix this.

**Comment by SteffanPoulsen** [comment]
Hi Rykazz, I took a quick look under the hood of Tidy5e-Sheet, and it seems that his naming of classes isn't quite following the sheet standard, which is causing some problems. You can fix it yourself if you can do some minor html editing.

Replace the following lines in these files and it should work:

**modules\tidy5e-sheet\templates\parts\tidy5e-features.html**
Line 33. `<div class="item-name flexrow">` replace with `<div class="item-name flexrow rollable">`

**modules\tidy5e-sheet\templates\parts\tidy5e-inventory.html**
Line 36. `<div class="item-name flexrow">` replace with `<div class="item-name flexrow rollable">`

**modules\tidy5e-sheet\templates\parts\tidy5e-spellbook.html**
Line 56. `<div class="item-name flexrow">` replace with `<div class="item-name flexrow rollable">`

**modules\tidy5e-sheet\templates\npc\parts\tidy5e-npc-features.html**
Line 23. `<div class="item-name flexrow">` replace with `<div class="item-name flexrow rollable">`

**modules\tidy5e-sheet\templates\npc\parts\tidy5e-npc-spellbook.html**
Line 44. `<div class="item-name flexrow">` replace with `<div class="item-name flexrow rollable">`

I'll try and reach out to the developer behind the module, and see if I can get him to fix it for you.

**Comment by SteffanPoulsen** [comment]
I talked to the developer behind Tidy5e Sheet, and he was kind enough to help getting our modules to work together! There should be an update for both Dice Tooltip as well as Tidy5e Sheet in Foundry now.
