### ISSUE TITLE
Hit Dice: Undefined

### ISSUE THREAD

**Issue by crymic** [SteffanPoulsen/dice-tooltip#5]
Hello,
No matter what sheet, if you mouse over "short rest" the tool tip pops up with "Hit Dice: Undefined".

**Comment by SteffanPoulsen** [comment]
Hi Linith, I'm having trouble reproducing this - what module (if not default) are you using for character sheets?

**Comment by crymic** [comment]
![hit-dice](https://user-images.githubusercontent.com/14077263/87889891-bc7b1500-c9e8-11ea-9056-096c91530401.jpg)

default one, although all sheets are the same. Your mod is the only one on. Using latest stable version of foundry
0.6.5 and D&D 0.93

**Comment by SteffanPoulsen** [comment]
Hi Linith, I took the time to redo the short-rest tooltip code (it was kinda shoddy) - it should be fixed, as well as have support for multiclassing now! thx for reporting the issue!

v.1.0.6 with the fix should be live in Foundry now
